{
 "title": "FRADA Monitor",
 "description": "Pool Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{alias=\"Core\"}"
    }
   ]
  },
  {
   "title": "Current Epoch Progress",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 16, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{alias=\"Core\"}/432000 ",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot in Epoch (Core)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int {alias=\"Core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core Uptime MVPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - cardano_node_metrics_nodeStartTime_int{alias=\"Core\"})"
    }
   ]
  },
  {
   "title": "Local Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "UTC Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "KES Expiration",
   "type": "gauge",
   "description": "KES time remaining",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_remainingKESPeriods_int {alias=\"Core\"} * 129600 * 1",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Active Stake (₳)",
   "type": "stat",
   "description": "from leaderlog results",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cncli_active_stake {alias=\"Core\"} / 1000000 "
    }
   ]
  },
  {
   "title": "Delegators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "poolstats_delegators", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transactions processed (Core)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"Core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core System Health",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\", alias=\"Core\"}[1m])) * 100)",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes {alias=\"Core\"} / (node_memory_MemTotal_bytes {alias=\"Core\"})))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes {alias=\"Core\"} / node_memory_SwapTotal_bytes{alias=\"Core\"})) * 100",
     "legendFormat": "SWAP Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"Core\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"Core\"})",
     "legendFormat": "Disk Utilization"
    }
   ]
  },
  {
   "title": "Disk Left",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"Core\"} /1000000000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Peers Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int {alias=\"Core\"}",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "title": "Rate of Block height (0.05)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_blockNum_int[10m])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Leaderlog Epoch",
   "type": "stat",
   "description": "From CNCLI",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "cncli_epoch" }
   ]
  },
  {
   "title": "RAM Free",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes {alias=\"Core\"}/1000000000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Peers In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_peers_in_count{alias=\"Core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "AssignedSlots",
   "type": "stat",
   "description": "From CNCLI",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cncli_epochSlots" }
   ]
  },
  {
   "title": "Estimated Blocks / Epoch",
   "type": "stat",
   "description": "From cncli results",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cncli_epochSlotsIdeal" }
   ]
  },
  {
   "title": "Relay 1 Uptime MVPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - cardano_node_metrics_nodeStartTime_int {alias=\"Relay 1\"})"
    }
   ]
  },
  {
   "title": "Chain Density",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot Schedule",
   "type": "table",
   "description": "From CNCLI",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 14 },
   "targets": [
    { "expr": "cncli_assignedSlots" }
   ]
  },
  {
   "title": "Relay 1 System Health",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\", alias=\"Relay 1\"}[1m])) * 100)",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"Relay 1\"} / (node_memory_MemTotal_bytes{alias=\"Relay 1\"})))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{alias=\"Relay 1\"} / node_memory_SwapTotal_bytes{alias=\"Relay 1\"})) * 100",
     "legendFormat": "SWAP Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\", alias=\"Relay 1\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\", alias=\"Relay 1\"})",
     "legendFormat": "Disk Utilization"
    }
   ]
  },
  {
   "title": "Disk Left",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"Relay 1\"} /1000000000)",
     "legendFormat": "Relay 1"
    }
   ]
  },
  {
   "title": "Peers In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_peers_in_count{alias=\"Relay 1\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "RAM Free",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes {alias=\"Relay 1\"}/1000000000)",
     "legendFormat": "Relay 1"
    }
   ]
  },
  {
   "title": "Peers Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int {alias=\"Relay 1\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay 2 Uptime CONTABO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - cardano_node_metrics_nodeStartTime_int {alias=\"Relay 2\"})"
    }
   ]
  },
  {
   "title": "Epoch Nonce",
   "type": "stat",
   "description": "From CNCLI",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cncli_epochNonce" }
   ]
  },
  {
   "title": "Relay 1 System Health",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\", alias=\"Relay 2\"}[1m])) * 100)",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"Relay 2\"} / (node_memory_MemTotal_bytes{alias=\"Relay 2\"})))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{alias=\"Relay 2\"} / node_memory_SwapTotal_bytes{alias=\"Relay 2\"})) * 100",
     "legendFormat": "SWAP Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\", alias=\"Relay 2\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\", alias=\"Relay 2\"})",
     "legendFormat": "Disk Utilization"
    }
   ]
  },
  {
   "title": "Disk Left",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"Relay 2\"} /1000000000)",
     "legendFormat": "Relay 1"
    }
   ]
  },
  {
   "title": "Peers In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_peers_in_count{alias=\"Relay 2\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Major GC Core",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "cardano_node_metrics_RTS_gcMajorNum_int{alias=\"Core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slots Missed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 26 },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotsMissedNum_int {alias=\"Core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Lifetime ROA %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "poolstats_roa_lifetime{}", "legendFormat": "__auto", "target": "pool.roa_total", "type": "timeseries" }
   ]
  },
  {
   "title": "Blocks Assigned (EKG)",
   "type": "stat",
   "description": "since node restart -- from EKG",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_node_is_leader_int {alias=\"Core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Blocks Forged (EKG)",
   "type": "stat",
   "description": "since node restart -- from EKG",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int {alias=\"Core\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "RAM Free",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes {alias=\"Relay 2\"}/1000000000)",
     "legendFormat": "Relay 1"
    }
   ]
  },
  {
   "title": "Peers Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int {alias=\"Relay 2\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block sync speed (blocks / min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate (cardano_node_metrics_blockNum_int[150s]) *60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block Delay (in seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_s",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Disk Space Left in GB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} /1000000000",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core System Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1 {alias=\"Core\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5 {alias=\"Core\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15 {alias=\"Core\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "System Load Relay 1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1 {alias=\"Relay 1\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5 {alias=\"Relay 1\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15 {alias=\"Relay 1\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "System Load Relay 2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1 {alias=\"Relay 2\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5 {alias=\"Relay 2\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15 {alias=\"Relay 2\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Core Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"Core\"}[1h])) * 3600",
     "legendFormat": "Core 1h Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias=\"Core\"}[1h])) * 3600",
     "legendFormat": "Core 1h Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "Relay 1 Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"Relay 1\"}[1h])) * 3600",
     "legendFormat": "Relay 1 1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias=\"Relay 1\"}[1h])) * 3600",
     "legendFormat": "Relay 1 1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "Relay 2 Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"Relay 2\"}[1h])) * 3600",
     "legendFormat": "Relay 2 1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias=\"Relay 2\"}[1h])) * 3600",
     "legendFormat": "Relay 2 1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "Time Synchronization Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds {alias=\"Core\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds {alias=\"Core\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds {alias=\"Core\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "Time Synchronization Relay 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds {alias=\"Relay 1\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds {alias=\"Relay 1\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds {alias=\"Relay 1\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "Time Synchronization Relay 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds {alias=\"Relay 2\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds {alias=\"Relay 2\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds {alias=\"Relay 2\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  }
 ]
}