{
 "title": "Servers Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Monitoring Node System Health",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\", alias=\"Moniroting Node\"}[1m])) * 100)",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes {alias=\"Moniroting Node\"} / (node_memory_MemTotal_bytes {alias=\"Moniroting Node\"})))* 100",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes {alias=\"Moniroting Node\"} / node_memory_SwapTotal_bytes{alias=\"Moniroting Node\"})) * 100",
     "legendFormat": "SWAP Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"Moniroting Node\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"Moniroting Node\"})",
     "legendFormat": "Disk Utilization"
    }
   ]
  },
  {
   "title": "IP ADDRESS",
   "type": "text",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 0 },
   "options": {
    "content": "CORE NODE IP :       \n\nRELAY NODE 1 IP :     \n \nRELAY NODE 2 IP : "
   }
  },
  {
   "title": "CARDANO LOGS - CORE NODE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Leadership Check",
     "type": "logs",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "{job=\"cardano\"} |= `TraceStartLeadershipCheck`"
      }
     ]
    },
    {
     "title": "Not Leader",
     "type": "logs",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 6 },
     "targets": [
      {
       "expr": "{job=\"cardano\"} |= `TraceNodeNotLeader`"
      }
     ]
    },
    {
     "title": "Leader",
     "type": "logs",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 6 },
     "targets": [
      {
       "expr": "{job=\"cardano\"} |= `TraceNodeIsLeader`"
      }
     ]
    },
    {
     "title": "Block Forged",
     "type": "logs",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "{job=\"cardano\", host=\"Core-Node\"} |= `TraceForgedBlock`"
      }
     ]
    },
    {
     "title": "Block Adopted",
     "type": "logs",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "targets": [
      {
       "expr": "{job=\"cardano\", host=\"Core-Node\"} |= `TraceAdoptedBlock`"
      }
     ]
    },
    {
     "title": "Outcome Forge Event",
     "type": "logs",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "targets": [
      {
       "expr": "{job=\"cardano\", host=\"Core-Node\"} |= `OutcomeTraceForgeEvent`"
      }
     ]
    },
    {
     "title": "Block Fetch Server Send Block",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "{job=\"cardano\", host=\"Core-Node\"} |= `TraceBlockFetchServerSendBlock`",
       "source": "url",
       "type": "json",
       "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "ChainSync Header Server",
     "type": "logs",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 25 },
     "targets": [
      {
       "expr": "{job=\"cardano\", host=\"Core-Node\"} |= `ChainSyncHeaderServer:Info`",
       "source": "url",
       "type": "json",
       "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Chain DB Chain Extended",
     "type": "logs",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 25 },
     "targets": [
      {
       "expr": "{job=\"cardano\", host=\"Core-Node\"} |= `Chain extended`",
       "source": "url",
       "type": "json",
       "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Block Fetch Decision",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "{job=\"cardano\", host=\"Core-Node\"} |= `BlockFetchDecision`",
       "source": "url",
       "type": "json",
       "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Ip Subscription Error",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "{job=\"cardano\", host=\"Core-Node\"} |= `IpSubscription:Error`",
       "source": "url",
       "type": "json",
       "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Error Policy ",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "{job=\"cardano\", host=\"Core-Node\"} |= `ErrorPolicy`",
       "source": "url",
       "type": "json",
       "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    }
   ]
  },
  {
   "title": "CARDANO LOGS - RELAY NODE 1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Fetch Server Send Block",
     "type": "logs",
     "gridPos": { "h": 16, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "{job=\"cardano\", host=\"Relay-Node-1\"} |= `TraceBlockFetchServerSendBlock`",
       "source": "url",
       "type": "json",
       "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Block Fetch Client Info",
     "type": "logs",
     "gridPos": { "h": 16, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "{job=\"cardano\", host=\"Relay-Node-1\"} |= `BlockFetchClient:Info`",
       "source": "url",
       "type": "json",
       "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Block Fetch Decision Info",
     "type": "logs",
     "gridPos": { "h": 16, "w": 8, "x": 16, "y": 7 },
     "targets": [
      {
       "expr": "{job=\"cardano\", host=\"Relay-Node-1\"} |= `BlockFetchDecision:Info`",
       "source": "url",
       "type": "json",
       "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Chain Extended",
     "type": "logs",
     "gridPos": { "h": 12, "w": 14, "x": 5, "y": 23 },
     "targets": [
      {
       "expr": "{job=\"cardano\", host=\"Relay-Node-1\"} |= `Chain extended`",
       "source": "url",
       "type": "json",
       "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    }
   ]
  },
  {
   "title": "SECURITY LOGS - CORE NODE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "UFW",
     "type": "logs",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "{host=\"Core-Node\", job=\"ufw\"} | logfmt"
      }
     ]
    },
    {
     "title": "FAIL 2 BAN",
     "type": "logs",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
     "targets": [
      {
       "expr": "{host=\"Core-Node\", job=\"fail2ban\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "SECURITY LOGS - RELAY NODE 1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "UFW",
     "type": "logs",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "{host=\"Relay-Node-1\", job=\"ufw\"} | logfmt"
      }
     ]
    },
    {
     "title": "FAIL 2 BAN",
     "type": "logs",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
     "targets": [
      {
       "expr": "{host=\"Relay-Node-1\", job=\"fail2ban\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "SECURITY LOGS - MONITORING LOGS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "UFW",
     "type": "logs",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "{host=\"Monitoring-Node\", job=\"ufw\"} | logfmt"
      }
     ]
    },
    {
     "title": "FAIL 2 BAN",
     "type": "logs",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 10 },
     "targets": [
      {
       "expr": "{host=\"Monitoring-Node\", job=\"fail2ban\"} |= ``"
      }
     ]
    }
   ]
  }
 ]
}